{{- $anyValue := false -}}
{{- range $k, $v := .Values.secretEnv -}}
  {{- if $v -}}{{- $anyValue = true -}}{{- end -}}
{{- end -}}
{{- if $anyValue -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watchtower.secretName" . }}
  labels:
    {{- include "watchtower.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
